### ISSUE TITLE
Schreibe Systemidee

### ISSUE THREAD

**Issue by Daniel-Seifert** [sweIhm-ws2018-19/skillproject-fr-15#21]

**Comment by Daniel-Seifert** [comment]
Systemidee Alexa's escape

In dem interactiven Escape-Game "Alexa's escape" geht es um den Ausbruch aus einem fremden Haus durch geschicktes Kombinieren verschiedener Gegenstände und Indizien. In dem fiktiven Szenario eines panischen Anrufes der Freundin "Alexa", welche sich in einem femden Haus widerfindet und versucht der brenzlichen Situation zu entkommen, muss der Spieler unter Zeitdruck die von "Alexa" beschriebenen Räume und deren Inhalt analysieren, um aus besagtem Haus zu entkommen. Der Zeitdruck kann hier in Form von unerwarteten Ereignissen nach einer gewissen Anzahl an Fehlversuchen, oder sogar durch Abbruch des Spiels geschehen. Score (dauer) und weitere Statistiken werden durch den Verknüpften Spielernamen (kann evtl. auch zu Beginn jedes Spiels gesagt werden um mehrere Scores auf einem Gerät zu ermöglichen) erfasst und gespeichert.

**Comment by Curlie** [comment]
Jetzt habe ich gerade auch eine Systemidee verfasst nur um festzustellen, dass beide ziemlich deckungsgleich sind :). Zusätzlich/Alternativ habe ich noch:
- nach einer festen Zeit ist das Spiel vorbei, d.h. Alexa wurde entdeckt
- Fehlentscheidungen verkürzen diese vorgegebene Zeit
- Alexa muss sich von Raum zu Raum "durchkämpfen"

**Comment by g3ner4l123** [comment]
Systemidee:
Alexas Escape ist ein interaktives Adventure-Spiel. In dem es darum geht dem fiktiven Charakter Alexa, über das Telefon zu helfen aus einem Haus zu helfen.
Dies wird bewerkstelligt indem man von Alexa Informationen über Standort und Umgebung von Alexa erhält und gibt ihr dann Anweisungen Diese Anweisungen können Raumwechsel, das Aufheben und Nutzen von Items oder ähnliche Aktionen sein.Die Spielwelt besteht aus einem beschränkten Berech, dem Haus und es gibt eine feste Zahl von Items, die zufällig darin verteilt sind. Die Items werden dann verwendet um sich weiter vor zu arbeiten (z.B. Schlüssel um eine Tür zu öffnen). Das Spielziel ist möglichst schnell einen Weg nach draußen zu finden. Die erzielte Zeit kann dann auf einem Leaderbord gespeichert und bei Abfrage wiedergegeben werden.
Mögliche Erweiterungen wären mehrere verschiedene Ausbruchsmöglichkeiten bzw. auch Fehlversuche, wenn man zu langsam ist oder Alexa stirbt/in eine ausgangslose Situation gerät.
 Zudem kann man natürlich immer neue Räume und Items einführen.
