### ISSUE TITLE
Mehrere Versuche

### ISSUE THREAD

**Issue by Lenz-K** [sweIhm-ws2018-19/skillproject-fr-15#34]
Als Spieler möchte ich mehrmals Spielen können, um meine Zeit zu verbessern oder das Spiel überhaupt erfolgreich zu beenden. Dies ist erfüllt wenn ich das Spiel unter dem gleichen Namen neu beginnen kann.

**Comment by Curlie** [comment]
Funktioniert super - also alle drei Issues!
Mir ist nur aufgefallen, dass bei der ersten Abfrage ("Highscore für Alfred nachschauen") irgendetwas Komisches passiert. Die Nachricht sollte ja eigentlich gar nicht definiert sein und somit auch nicht erkannt werden. Ist wahrscheinlich mal wieder irgendein Developer Console Bug ;)...
![grafik](https://user-images.githubusercontent.com/7760206/49926474-e63e9280-febb-11e8-987c-b3766ffff19d.png)

**Comment by Lenz-K** [comment]
Einzige Anmerkung meinerseits: Die "SolveDescription" vom letzten Raum wird nicht aufgerufen.

**Comment by Daniel-Seifert** [comment]
Ich fix das schnell

**Comment by Daniel-Seifert** [comment]
Würde ich in den nächsten Sprint verschieben
