### ISSUE TITLE
Soundeffekte

### ISSUE THREAD

**Issue by Lenz-K** [sweIhm-ws2018-19/skillproject-fr-15#35]
Als Spieler möchte ich Soundeffekte hören, damit das Spiel möglichst realistisch ist. Dies ist der Fall, wenn an mindestens fünf Stellen im Spiel ein Soundeffekt zu hören ist.

**Comment by Lenz-K** [comment]
Hab mal paar Sounds von Amazon eingebaut. Ihr könnt ja mal sagen wie ihrs findet. Ich werde aber auch noch versuchen eigene Sounds einzubauen, weil die Sounddatenbank von amazon nicht so ergibig ist.

**Comment by Lenz-K** [comment]
Infos über Spracheinstellungen:
https://developer.amazon.com/de/docs/custom-skills/speech-synthesis-markup-language-ssml-reference.html
könnten wir einbauen.

**Comment by Lenz-K** [comment]
Amazon Sound Library:
https://developer.amazon.com/de/docs/custom-skills/ask-soundlibrary.html

**Comment by Curlie** [comment]
hört sich gut an :). Stimmen und Effekte würde ich - wie besprochen - auf Alexa Standard lassen.

**Comment by Lenz-K** [comment]
Und in Sprint 3 dann noch eigene Soundeffekte

**Comment by Curlie** [comment]
Damit bin ich einverstanden.
