### ISSUE TITLE
Hilfe

### ISSUE THREAD

**Issue by g3ner4l123** [sweIhm-ws2018-19/skillproject-fr-15#41]
Als Spieler möchte ich zu Beginn es Spieles die Möglichkeit haben mit das Spiel Erklären zu lassen. Die Anforderung ist erfüllt, wenn ich im Hauptmenü eine Hilfe-Option habe.

**Comment by Curlie** [comment]
Für Sprint 3 könnte man sich vormerken, dass man für die verschiedenen Stati jeweils eine Statusbezogene hilfestellung bekommt.

**Comment by Curlie** [comment]
Ich glaube wir benötigen für den IntentHandler noch den Intent in der Developer Konsole. Mir wird da keiner angezeigt und ich kann die Hilfe auch nicht aufrufen.

**Comment by Lenz-K** [comment]
Jetzt passt es!
