### ISSUE TITLE
Wiederholen:

### ISSUE THREAD

**Issue by Curlie** [sweIhm-ws2018-19/skillproject-fr-15#43]
Als Spieler möchte ich jederzeit die letzte Sprachausgabe wiederholen lassen, damit keine Missverständnisse auftreten.
Erfüllt ist diese Anforderung, sobald ich in jedem Zustand durch "wiederhole" o.Ä. mir die Sprachausgabe nochmal anhören kann

**Comment by Lenz-K** [comment]
Perfekt
