### ISSUE TITLE
Highscore:

### ISSUE THREAD

**Issue by Curlie** [sweIhm-ws2018-19/skillproject-fr-15#44]
Als Spieler möchte ich mir vor und nach dem Spiel meinen derzeitigen Highscore ausgeben lassen, um mich mit meiner bisherigen Bestzeit zu vergleichen.
Die Funktionalität ist gegeben, sobald ich eine Ausgabe von meiner Bestzeit ansteuern kann.

**Comment by Daniel-Seifert** [comment]
Das aktuelle Schema des Highscores in der Dynamo ist folgendes

![image](https://user-images.githubusercontent.com/31901828/49028526-e2fc9480-f1a2-11e8-823c-693d9253d0c9.png)

**Comment by Lenz-K** [comment]
All good
