### ISSUE TITLE
Vielfalt der Gegenstände:

### ISSUE THREAD

**Issue by Curlie** [sweIhm-ws2018-19/skillproject-fr-15#46]
Als Spieler möchte ich pro Raum aus mehreren Gegenständen auswählen können, um mehr Auswahlmöglichkeiten zu haben.
Sobald in jedem Raum mehr als drei Gegenstände sind, ist die Anforderung erfüllt

**Comment by Lenz-K** [comment]
Anforderung wäre erfüllt

**Comment by Curlie** [comment]
Code passt; ggf. könnte man noch die Anzahl der Items variabel gestalten. (Sprint 3?)

**Comment by Lenz-K** [comment]
Ja, Ich würde sagen wir machen In Sprint 3 alles variabel was noch nicht variabel ist.

**Comment by Curlie** [comment]
Gut.
