### ISSUE TITLE
Sprachsteuerung /-erkennung

### ISSUE THREAD

**Issue by Lenz-K** [sweIhm-ws2018-19/skillproject-fr-15#60]
Als Spieler möchte ich, dass die Sprachsteuerung gut funktioniert.
Dies ist erfüllt wenn die Sprachsteuerung meistens funktioniert.

**Comment by Lenz-K** [comment]
ToDo: ItemSlot mit ItemNamen vorbelegen

**Comment by Curlie** [comment]
Funktion wurde umgesetzt. Bitte Rückmeldung, falls es nicht funktionieren sollte

**Comment by Curlie** [comment]
Funktionierte heute mit dem Alexa Lautsprecher (oder wie auch immer das Teil heißt).

**Comment by g3ner4l123** [comment]
Hab es auch nochmal getestet bei mir funktioniert es auch alles - Closed.
