### ISSUE TITLE
Viele Soundeffekte

### ISSUE THREAD

**Issue by Lenz-K** [sweIhm-ws2018-19/skillproject-fr-15#61]
Als Spieler möchte ich viele Soundeffekte im Spiel hören, damit das Spiel möglichst realistisch ist.
Dies ist erfüllt wenn im Skill mindestens 10 Soundeffekte vorhanden sind.

**Comment by Lenz-K** [comment]
Es gibt jetzt 10 verschiedene Soundeffekte. Wenn noch Items dazukommen, könnte man noch Soundeffekte hinzufügen...

**Comment by Curlie** [comment]
Hört sich nice an ;). Sollte reichen.
