### ISSUE TITLE
Viele Items

### ISSUE THREAD

**Issue by Lenz-K** [sweIhm-ws2018-19/skillproject-fr-15#62]
Als Spieler möchte ich, dass es im Spiel viele verschiedene Items gibt, damit das Spiel auch nach mehrmaligem Spielen abwechslungsreich bleibt.
Dies ist erfüllt wenn es mindestens 12 verschiedene Items gibt.

**Comment by g3ner4l123** [comment]
Es wurden zwei weitere Container und mehrere normale Items hinzugefügt.
Das Ganze wurde in der Console getestet und funktioniert - zumindest bei mir - alles fehlerfrei.

**Comment by Lenz-K** [comment]
Passt!
