### ISSUE TITLE
Natürlicher Gesprächsfluss

### ISSUE THREAD

**Issue by Lenz-K** [sweIhm-ws2018-19/skillproject-fr-15#63]
Als Spieler möchte ich, dass der Gesprächsfluss möglichst natürlich wirkt.

**Comment by Lenz-K** [comment]
Die letzte solveDescription soll aufgerufen werden

**Comment by Lenz-K** [comment]
Häufigkeit der Raumbeschreibung reduzieren

**Comment by Curlie** [comment]
solvedescription und loosedescription passen jetzt:
![grafik](https://user-images.githubusercontent.com/7760206/50345422-4faf4880-052f-11e9-9150-900bd7c1e180.png)
![grafik](https://user-images.githubusercontent.com/7760206/50345437-5ccc3780-052f-11e9-84fd-f16c7937ed43.png)

**Comment by Lenz-K** [comment]
Sollen wir die Häufigkeit der Raumbeschreibungen reduzieren (nur bei einem neuen Raum und auf Anfrage) oder passt es so? (Man vergisst ja schnell was alles im Raum ist)

**Comment by Curlie** [comment]
also ich kann mir zumindest eher schwer die ganzen Gegenstände im Raum merken, wenn ich es nur durch Alexa höre. Somit würde ich die Beschreibung jedesmal ausgeben lassen. Denn wenn man dann jedesmal darum bitten muss, die Items zu wiederholen, wird das auf Dauer etwas blöd, denke ich.

**Comment by Lenz-K** [comment]
alles klar
